@@ To update !!!!
version: "3"
services: 

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett_
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Baku
      - AUTO_UPDATE=true #optional
    volumes:
      - /home/maxime/Documents//container/jackett/config:/config
      - /home/maxime/Documents/media/torrent:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin_
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Baku
    volumes:
      - /home/maxime/Documents//container/jellyfin/config:/config
      - /home/maxime/Documents/media/tvshows:/data/tvshows
      - /home/maxime/Documents/media/tvshows2:/data/tvshows2
      - /home/maxime/Documents/media/movies:/data/movies
      - /home/maxime/Documents/media/movies2:/data/movies2
      - /home/maxime/Documents/media/disney:/data/disney
      - /home/maxime/Documents/media/disney2:/data/disney2
      - /home/maxime/Documents/media/anime:/data/anime
      - /home/maxime/Documents/media/anime2:/data/anime2
      - /home/maxime/Documents/media/musics:/data/music
    ports:
      - 8096:8096
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr_
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Baku
    volumes:
      - /home/maxime/Documents/container/lidarr/config:/config
      - /home/maxime/Documents/media/musics:/music #optional
      - /home/maxime/Documents/media/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr_
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Baku
    volumes:
      - /home/maxime/Documents/container/radarr/config:/config
      - /home/maxime/Documents/media/downloads:/downloads
      - /home/maxime/Documents/media/movies:/data/movies
      - /home/maxime/Documents/media/movies2:/data/movies2
      - /home/maxime/Documents/media/disney:/data/disney
      - /home/maxime/Documents/media/disney2:/data/disney2
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr_
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Baku
    volumes:
      - /home/maxime/Documents/container/sonarr/config:/config
      - /home/maxime/Documents/media/tvshows:/data/tvshows
      - /home/maxime/Documents/media/tvshows2:/data/tvshows2
      - /home/maxime/Documents/media/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge_
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Baku
    volumes:
      - /home/maxime/Documents/container/deluge/config:/config
      - /home/maxime/Documents/media/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped


  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex_server
    network_mode: host
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
#      - PLEX_CLAIM= #optional
    volumes:
      - /home/maxime/Documents/container/plex/config:/config
      - /home/maxime/Documents/media/tvshows:/data/tvshows
      - /home/maxime/Documents/media/tvshows2:/data/tvshows2
      - /home/maxime/Documents/media/movies:/data/movies
      - /home/maxime/Documents/media/movies2:/data/movies2
      - /home/maxime/Documents/media/disney:/data/disney
      - /home/maxime/Documents/media/disney2:/data/disney2
      - /home/maxime/Documents/media/anime:/data/anime
      - /home/maxime/Documents/media/anime2:/data/anime2
    restart: unless-stopped
    
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr_
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Baku
   # DOCKER_MODS=wayller/bazarr-mod-subsync:latest
    volumes:
      - /home/maxime/Documents/container/bazarr/config:/config
      - /home/maxime/Documents/media/tvshows:/data/tvshows
      - /home/maxime/Documents/media/tvshows2:/data/tvshows2
      - /home/maxime/Documents/media/movies:/data/movies
      - /home/maxime/Documents/media/movies2:/data/movies2
      - /home/maxime/Documents/media/disney:/data/disney
      - /home/maxime/Documents/media/disney2:/data/disney2
      - /home/maxime/Documents/media/anime:/data/anime
      - /home/maxime/Documents/media/anime2:/data/anime2
    ports:
      - 6767:6767
    restart: unless-stopped
