--- 
version: "2"
services: 
  db:
    image: "mariadb:10.5"
    restart: always
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW"
    environment: 
      - MYSQL_ROOT_PASSWORD=Max2019!
      - MYSQL_PASSWORD=maxime
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes: 
      - /opt/container/nextcloud/db:/var/lib/mysql 
  
  
  app: 
    image: nextcloud
    restart: always
    depends_on: 
      - db
    links: 
      - db
    ports: 
      - "8080:80" 
    volumes: 
      - /opt/container/nextcloud/nextcloud:/var/www/html
      - /opt/container/nextcloud/app/custom_apps:/var/www/html/custom_apps
      - /opt/container/nextcloud/app/config/var/www/html/config
      - /opt/container/nextcloud/app/data:/var/www/html/data
      - /opt/container/nextcloud/app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_PASSWORD=maxime
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
